services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile.transmission
    container_name: transmission
    restart: always
    environment:
      - DOCKER_MODS=linuxserver/mods:transmission-env-var-settings
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TR_USER}
      - PASS=${TR_PASSWORD}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/convert-to-mp4.sh
      - TR_DOWNLOAD_PATH=${TR_DOWNLOAD_PATH:-/var/lib/transmission-daemon/downloads}
      - TR_CONFIG_PATH=${TR_CONFIG_PATH:-/var/lib/transmission-daemon/config}
      - TR_WATCH_PATH=${TR_WATCH_PATH:-/var/lib/transmission-daemon/watch}
    volumes:
      - ${TR_DOWNLOAD_PATH}:/downloads
      - ${TR_CONFIG_PATH}:/config
      - ${TR_WATCH_PATH}:/watch
      - ./convert-to-mp4.sh:/convert-to-mp4.sh
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    healthcheck:
      test: [ "CMD", "curl", "-s", "-o", "/dev/null", "http://localhost:9091/transmission/rpc" ]
      interval: 5s
      timeout: 10s
      retries: 3
  server:
    build:
      context: .
      dockerfile: Dockerfile.bun
    container_name: liveseries
    restart: always
    environment:
      - TRANSMISSION_URL=http://transmission:9091/transmission/rpc
      - TR_APPEND_COMPLETE_TO_DOWNLOAD_PATH=true
      - TR_DOWNLOAD_PATH=/downloads
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ${TR_DOWNLOAD_PATH}:/downloads
    ports:
      - "${APP_PORT:-80}:3000"
    depends_on:
      transmission:
        condition: service_healthy

volumes:
  mariadb_data:
