services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=liveseries
      - MARIADB_USER=${MY_SQL_DB_USER}
      - MARIADB_PASSWORD=${MY_SQL_DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - DOCKER_MODS=linuxserver/mods:transmission-env-var-settings
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TR_USER}
      - PASS=${TR_PASSWORD}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/convert-to-mp4.sh
      - TR_DOWNLOAD_PATH=${TR_DOWNLOAD_PATH:-/var/lib/transmission-daemon/downloads}
      - TR_CONFIG_PATH=${TR_CONFIG_PATH:-/var/lib/transmission-daemon/config}
      - TR_WATCH_PATH=${TR_WATCH_PATH:-/var/lib/transmission-daemon/watch}
    volumes:
      - $TR_DOWNLOAD_PATH:/downloads
      - $TR_CONFIG_PATH:/config
      - $TR_WATCH_PATH:/watch
      - ./convert-to-mp4.sh:/convert-to-mp4.sh
      - ./whitelist.json:/app/whitelist.json
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  server:
    build: .
    container_name: liveseries
    restart: always
    environment:
      - MY_SQL_DB_NAME=liveseries
      - TR_APPEND_COMPLETE_TO_DOWNLOAD_PATH=true
    ports:
      - "${APP_PORT:-80}:5021"
    depends_on:
      - db
      - transmission

volumes:
  mariadb_data:
