services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME:-liveseries}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  transmission:
    image: liveseries/transmission
    container_name: transmission
    restart: always
    environment:
      - DOCKER_MODS=linuxserver/mods:transmission-env-var-settings
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TR_USER}
      - PASS=${TR_PASSWORD}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/convert-to-mp4.sh
      - TRANSMISSION_PEER_PORT=49917
      - TR_DOWNLOAD_PATH=/downloads
      - TR_CONFIG_PATH=/config
      - TR_WATCH_PATH=/watch
    volumes:
      - ${TR_DOWNLOAD_PATH:-/var/lib/transmission-daemon/downloads}:/downloads
      - ${TR_CONFIG_PATH:-/var/lib/transmission-daemon/config}:/config
      - ${TR_WATCH_PATH:-/var/lib/transmission-daemon/watch}:/watch
      - ./convert-to-mp4.sh:/convert-to-mp4.sh
    ports:
      - 9091:9091
      - 49917:49917
      - 49917:49917/udp
    healthcheck:
      test: [ "CMD", "curl", "-s", "-o", "/dev/null", "http://localhost:9091/transmission/rpc" ]
      interval: 5s
      timeout: 10s
      retries: 3
  migrations:
    image: liveseries/migrations
    container_name: migrations
    restart: no
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
  server:
    image: liveseries/server
    container_name: liveseries
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
      transmission:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - TRANSMISSION_URL=http://transmission:9091/transmission/rpc
      - TR_DOWNLOAD_PATH=/downloads
      - TR_APPEND_COMPLETE_TO_DOWNLOAD_PATH=true
      - LOG_TO_CONSOLE=true
      - APP_PORT=5017
      - SUBTITLE_CACHE_PATH=/subtitles
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ./.env:/app/.env
      - ${TR_DOWNLOAD_PATH}:/downloads
      - ${SUBTITLE_CACHE_PATH}:/subtitles
    ports:
      - "${APP_PORT:-5017}:5017"
volumes:
  postgres_data:
