FROM node:22.12-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# Fails the build if they are not present
COPY .env whitelist.json ./

ENV NODE_ENV=production
ENV NODE_PORT=5021
ENV LOG_TO_CONSOLE='true'

COPY . .
RUN npm run compile
EXPOSE 5021
CMD ["node", "dist/index.js"]
