name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Typecheck (tsgo)
        run: bun run types:check:go
        if: always()

      - name: Typecheck
        run: bun run types:check
        if: always()

      - name: Build application
        run: bun run build
        if: always()

  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-buildx-cache

      - name: Run deploy script (dry run)
        run: BUILDX_CACHE_DIR=/tmp/.buildx-cache ./deploy.sh --dry-run
